### ISSUE TITLE
Add page/dialog for loading saved csv files

### ISSUE THREAD

**Issue by MaxDillon** [phil208-ethics-project/phil208-ethics-project.github.io#4]
### Notes
- use current upload/download buttons implemented in [pull/2
](https://github.com/phil208-ethics-project/phil208-ethics-project.github.io/pull/2)
### Todo
- [ ] verify uploaded files have the correct extension and meet the proper format
- [ ] handle errors involved in reading I/O
- [ ] push file data to Dexie 
- [ ] create clear visual language around download/upload workflow
  - Possibly use popup dialog for upload
  - Option to upload zip files
  - Option to upload files individually? (buttons/drag'n'drop for each table?)

**Comment by SeanMcGuckin** [comment]
- Add written dialogue, visuals, and directions to the StudentPage.tsx file
- Make a function to produce a file drop in box below the student table
  - This would be a component under Student DashBoard
- On click of the file upload, activate a function on the input to check the following:
  - File type 
  - Headers
    - I assume order of headers shouldn't matter for dexie but we'll figure that out later
- Push to dexie probably has some sort of tutorial and should be inferable from student table / dashboard code

**Comment by SeanMcGuckin** [comment]
Making drag and drop in react + ts: 

https://claritydev.net/blog/react-typescript-drag-drop-file-upload-guide

**Comment by SeanMcGuckin** [comment]
SaveData/lib/readFile can be helpful
